import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WebSocket} from 'ws';import {Store} from '../src/store.js';import {Rooms} from '../src/rooms.js';import {resolve,wall,valid} from '../src/combat.js';import {createServer} from '../src/main.js';
const rows=readFileSync(new URL('../../shared-fixtures/combat.csv',import.meta.url),'utf8').trim().split(/\r?\n/).slice(1).map(s=>s.split(','));
for(const scenario of new Set(rows.map(r=>r[0])))test('shared C# parity: '+scenario,()=>{const group=rows.filter(r=>r[0]===scenario);const result=resolve(group.map(r=>({id:r[1],hp:+r[2]})),group.filter(r=>+r[2]>0).map(r=>({id:r[1],position:{x:+r[3],y:+r[4]},direction:{x:+r[5],y:+r[6]},canThrow:r[7]==='true'})));
  for(const r of group){assert.equal(result.health.find(h=>h.id===r[1])!.after,+r[8]);assert.equal(result.throws.find(t=>t.thrower===r[1])?.target??'',r[9]);}assert.equal(result.outcome,group[0][10]);});
test('rounded boundary grid and rays',()=>{for(let angle=0;angle<360;angle++){const p=wall({x:0,y:0},{x:Math.cos(angle*Math.PI/180),y:Math.sin(angle*Math.PI/180)});assert.equal(valid(p,30),true);}assert.equal(valid({x:950,y:1700}),false);});
for(const count of [2,3,6])test(`${count} players privacy, simultaneous ready, complete match and reward once`,()=>{const s=new Store(':memory:');let now=1000;const rooms=new Rooms(s,()=>now);const ids=Array.from({length:count},(_,i)=>s.guest('P'+i).id);const r=rooms.create(ids[0]);for(const id of ids.slice(1))rooms.join(id,r.code);for(const id of ids)rooms.ready(id,true);assert.equal(r.phase,'Countdown');now+=3000;rooms.tick();assert.equal(r.phase,'Placement');
  for(let round=1;round<=3;round++){
    for(let i=0;i<count;i++){rooms.action(ids[i],round*3-2,'place',{x:-600+i*200,y:0},round);rooms.action(ids[i],round*3-1,'aim',{x:1,y:0},round);const snap=rooms.snapshot(ids[i])!;assert(snap.players.filter(p=>p.id!==ids[i]).every(p=>p.action===null));rooms.action(ids[i],round*3,'lock',null,round);}
    assert.equal(r.phase,'Reveal');assert.throws(()=>rooms.action(ids[0],round*3+1,'place',{x:0,y:0},round),/action_locked/);assert.deepEqual(rooms.action(ids[0],round*3,'lock',null,round),{duplicate:true});
    now+=300;rooms.tick();now+=700;rooms.tick();now+=600;rooms.tick();
  }
  assert.equal(r.phase,'MatchResult');const balance=s.profile(ids[0]).coins;s.reward(r.match,ids,r.resolution!.winner,true,true);assert.equal(s.profile(ids[0]).coins,balance);assert.equal(s.profile(ids[0]).history.length,1);assert(s.profile(ids[0]).inventory.some((x:any)=>x.item==='LangQueBacBo'));s.close();});
test('timeout proposal, reconnect private snapshot, waiting disconnect expiry and code expiry',()=>{const s=new Store(':memory:');let now=1;const rooms=new Rooms(s,()=>now,true,1000),a=s.guest('A').id,b=s.guest('B').id,r=rooms.create(a);rooms.join(b,r.code);rooms.ready(a,true);rooms.ready(b,true);now+=3000;rooms.tick();rooms.action(a,1,'place',{x:500,y:0},1);rooms.disconnect(a);rooms.reconnect(a);assert.equal(rooms.snapshot(b)!.players.find(p=>p.id===a)!.action,null);now+=5000;rooms.tick();assert.equal(r.phase,'Reveal');assert(r.players.every(p=>!p.action!.canThrow));
  const c=s.guest('C').id,wait=rooms.create(c);rooms.disconnect(c);now+=1001;rooms.tick();assert(!rooms.membership.has(c));assert.throws(()=>rooms.join(s.guest('D').id,wait.code));s.close();});
test('unconfirmed timeout blocks without invented action',()=>{const s=new Store(':memory:');let now=0;const rooms=new Rooms(s,()=>now,false),a=s.guest('A').id,b=s.guest('B').id;const r=rooms.create(a);rooms.join(b,r.code);rooms.ready(a,true);rooms.ready(b,true);now=3000;rooms.tick();now=8000;rooms.tick();assert.equal(r.phase,'RequirementsBlocked');assert.equal(r.resolution,null);s.close();});
test('durable guest token, inventory, ledger and private farm cap',()=>{const dir=mkdtempSync(join(tmpdir(),'hitme-'));const path=join(dir,'test.sqlite');let s=new Store(path);const a=s.guest('A'),b=s.guest('B');for(let i=0;i<4;i++)s.reward('match'+i,[a.id,b.id],a.id,true,true);assert.equal(s.profile(a.id).coins,300);s.equip(a.id,'chao');s.close();s=new Store(path);assert.equal(s.guest('',a.token).id,a.id);assert.equal(s.profile(a.id).equipped,'chao');assert.equal(s.profile(a.id).coins,300);assert.throws(()=>s.guest('','fake'));assert.throws(()=>s.equip(a.id,'damage-upgrade'));s.close();rmSync(dir,{recursive:true});});
test('quest events dedupe and claim exactly once',()=>{const s=new Store(':memory:'),a=s.guest('A').id;s.event('same',a,'ValidHit');s.event('same',a,'ValidHit');const q=s.quests(a).find(q=>q.kind==='ValidHit'&&q.period.length===10)!;assert.equal(q.progress,1);s.claim(a,q.period,q.kind);assert.throws(()=>s.claim(a,q.period,q.kind));s.db.prepare('INSERT INTO quests(player,period,kind,progress) VALUES(?,?,?,?)').run(a,'1999-01-01','ValidHit',1);assert.equal(s.profile(a).expiredQuests[0].state,'Expired');s.close();});
test('real WebSocket auth, room join, resume and unauthorized reward rejection',async()=>{const s=new Store(':memory:'),app=createServer(s);await new Promise<void>(resolve=>app.server.listen(0,'127.0.0.1',resolve));const port=(app.server.address() as any).port;
  async function client(){const ws=new WebSocket(`ws://127.0.0.1:${port}/play`);const inbox:any[]=[];ws.on('message',raw=>inbox.push(JSON.parse(raw.toString())));await new Promise(resolve=>ws.once('open',resolve));let serial=0;return {ws,inbox,send:(type:string,value:any={})=>ws.send(JSON.stringify({type,request:'r'+(++serial),...value})),wait:async(predicate:(m:any)=>boolean)=>{const until=Date.now()+2000;while(Date.now()<until){const m=inbox.find(predicate);if(m)return m;await new Promise(r=>setTimeout(r,10));}throw Error('message timeout');}};}
  try{const a=await client(),b=await client();a.send('hello',{name:'A'});b.send('hello',{name:'B'});const auth=await a.wait(m=>m.type==='welcome');await b.wait(m=>m.type==='welcome');a.send('create');const room=(await a.wait(m=>m.type==='state'&&m.room)).room;b.send('join',{code:room.code});await b.wait(m=>m.type==='state'&&m.room?.players.length===2);a.send('reward',{coins:9999});assert.equal((await a.wait(m=>m.type==='error')).message,'unsupported_request');assert.equal(s.profile(auth.id).coins,0);a.ws.close();await new Promise(r=>setTimeout(r,30));const resumed=await client();resumed.send('hello',{token:auth.token});assert.equal((await resumed.wait(m=>m.type==='welcome')).id,auth.id);assert.equal((await resumed.wait(m=>m.type==='state'&&m.room)).room.code,room.code);
  }finally{await app.close();s.close();}});
