using System.IO;
using HitMe.Characters;
using HitMe.Visuals;
using UnityEngine;
using UnityEditor;
using UnityEditor.U2D;
using UnityEngine.U2D;
namespace HitMe.Editor {
public static class MasterProductionSetup {
 const string ResourcesRoot="Assets/HitMe/Resources/Production/";
 static T Asset<T>(string name) where T:ScriptableObject {string path=ResourcesRoot+name+".asset";var data=AssetDatabase.LoadAssetAtPath<T>(path);if(data==null){data=ScriptableObject.CreateInstance<T>();AssetDatabase.CreateAsset(data,path);}return data;}
 static EnvironmentLayerDefinition Layer(string id,string sprite,Vector2 anchor,Vector2 size,LayerMotion motion){var d=Asset<EnvironmentLayerDefinition>(id);d.layerId=id;d.sprite=ProductionArtSetup.Sprite("Environments/"+sprite+".png");d.anchor=anchor;d.referenceSize=size;d.motion=motion;d.amplitude=motion==LayerMotion.Crowd?.6f:2;d.pivot=new Vector2(.5f,1);d.provenance="Independent AI-derived static cutout. Whole-sprite motion fallback, no cloth/leaf rig.";EditorUtility.SetDirty(d);return d;}
 [MenuItem("HIT ME/Configure Master Production Pack")]
 public static void Configure(){Directory.CreateDirectory(ResourcesRoot);AssetDatabase.Refresh();ProductionArtSetup.Configure();var pack=Asset<ProductionVisualPack>("VisualPack");
  string[] ids={"BlackBoy","PinkGirl","BlondBoy","NonLaBoy","CapBoy","GoldenDog","BlackCat"};string[] names={"Nam tóc đen","Nữ tóc hồng","Nam tóc vàng","Nón lá","Mũ lưỡi trai","Chó vàng","Mèo mun"};pack.roster=new CharacterDefinition[7];
  for(int i=0;i<ids.Length;i++){var d=Asset<CharacterDefinition>(ids[i]);d.characterId="Visual_"+ids[i];d.displayName=names[i];d.artBrief="Static production showcase. Six states use procedural visual motion; no invented frames or online ID.";d.referenceHeight=74;d.visualScale=1;d.footPivot=new Vector2(i==3?.28f:i==4?.23f:.5f,0);var sprite=i==0?AssetDatabase.LoadAssetAtPath<Sprite>("Assets/HitMe/Art/Characters/Char01_Player/Idle/frame_000.png"):ProductionArtSetup.Sprite(i==1?"Characters/pink-static-preview.png":(i>4?"Animals/":"Characters/")+ids[i]+".png");d.animations=new[]{new CharacterAnimation{state=VisualState.Idle,frames=new[]{sprite},loop=true,framesPerSecond=1}};d.portrait=ProductionArtSetup.Sprite("Characters/Portraits/"+ids[i]+".png");d.shadow=AssetDatabase.LoadAssetAtPath<HitMe.UI.UIThemeDefinition>("Assets/HitMe/Resources/UI/MainMenuTheme.asset").shadow;d.motionProfile=Resources.Load<CharacterMotionProfile>("Motion/Character");d.defaultWeapon=null;EditorUtility.SetDirty(d);pack.roster[i]=d;}
  string[] weapons={"Slipper","Smartphone","MosquitoRacket","PickleballPaddle","BeerMug","FryingPan","Television","Refrigerator","PlasticStool"};pack.weapons=new WeaponDefinition[weapons.Length];
  for(int i=0;i<weapons.Length;i++){var d=Asset<WeaponDefinition>(weapons[i]);d.weaponId="Visual_"+weapons[i];d.displayName=weapons[i];d.heldSprite=d.projectileSprite=d.icon=i==0?AssetDatabase.LoadAssetAtPath<Sprite>("Assets/HitMe/Art/Weapons/DepToOng/held.png"):i==5?AssetDatabase.LoadAssetAtPath<Sprite>("Assets/HitMe/Art/Weapons/Chao/held.png"):ProductionArtSetup.Sprite("Weapons/"+weapons[i]+".png");d.visualSize=i>=6?12:14;d.gripPivot=new Vector2(.5f,.2f);d.flightSpinDegreesPerSecond=i==0?720:i>=6?120:360;d.trailEnabled=true;d.trailWidth=i>=6?2.1f:1.6f;d.trailColor=i==1?new Color(.4f,.8f,1,.28f):i>=6?new Color(.9f,.75f,.5f,.2f):new Color(1,.8f,.4f,.28f);EditorUtility.SetDirty(d);pack.weapons[i]=d;}
  var gameplayCatalog=CharacterCatalog.Load();string[] portraits={"BlackBoy","LegacyBotMale","LegacyBotFemale"};for(int i=0;i<3;i++){var existing=gameplayCatalog.characters[i];existing.portrait=ProductionArtSetup.Sprite("Characters/Portraits/"+portraits[i]+".png");EditorUtility.SetDirty(existing);}
  pack.centerLotus=ProductionArtSetup.Sprite("Environments/LotusMedallion.png");
  pack.menuLayers=new[]{Layer("MenuLantern","Lantern",new Vector2(.08f,.78f),new Vector2(32,65),LayerMotion.Sway),Layer("MenuLeaves","BanyanBranch",new Vector2(.93f,.92f),new Vector2(80,62),LayerMotion.Sway),Layer("MenuFlag","FestivalFlag",new Vector2(.94f,.7f),new Vector2(36,50),LayerMotion.Flutter),Layer("MenuForegroundTea","TeaProps",new Vector2(.90f,.60f),new Vector2(42,36),LayerMotion.Static)};
  pack.battleLayers=new[]{Layer("BattleCrowd","Audience",new Vector2(.5f,.865f),new Vector2(58,33),LayerMotion.Crowd),Layer("BattleLantern","Lantern",new Vector2(.04f,.83f),new Vector2(25,50),LayerMotion.Sway),Layer("BattleFlag","FestivalFlag",new Vector2(.96f,.83f),new Vector2(28,42),LayerMotion.Flutter),Layer("BattleLeaves","BanyanBranch",new Vector2(.92f,.12f),new Vector2(65,45),LayerMotion.Sway)};
  const string atlasPath=ProductionArtSetup.Root+"ProductionObjects.spriteatlas";var atlas=AssetDatabase.LoadAssetAtPath<SpriteAtlas>(atlasPath);if(atlas==null){atlas=new SpriteAtlas();AssetDatabase.CreateAsset(atlas,atlasPath);}atlas.Remove(atlas.GetPackables());atlas.Add(new Object[]{AssetDatabase.LoadAssetAtPath<Object>(ProductionArtSetup.Root+"Characters"),AssetDatabase.LoadAssetAtPath<Object>(ProductionArtSetup.Root+"Animals"),AssetDatabase.LoadAssetAtPath<Object>(ProductionArtSetup.Root+"Weapons"),pack.centerLotus,pack.menuLayers[0].sprite,pack.menuLayers[1].sprite,pack.menuLayers[2].sprite});atlas.SetPackingSettings(new SpriteAtlasPackingSettings{padding=4,enableRotation=false,enableTightPacking=false});atlas.SetTextureSettings(new SpriteAtlasTextureSettings{generateMipMaps=false,filterMode=FilterMode.Bilinear,sRGB=true});atlas.SetIncludeInBuild(true);EditorUtility.SetDirty(atlas);EditorUtility.SetDirty(pack);AssetDatabase.SaveAssets();Debug.Log("MASTER_PRODUCTION: seven static roster definitions, nine cosmetic prop definitions, independent environment layers. No gameplay/online IDs added.");
 }
 public static void Build(){Configure();MapKitSetup.Configure();HitMeWebBuild.BuildMasterProduction();}
}
}
