using System.IO;
using System.Collections.Generic;
using TMPro;
using HitMe.UI;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
namespace HitMe.Editor {
public static class UIKitSetup {
 const string Root="Assets/HitMe/Resources/UI/Kit/";
 public static readonly string[] WidgetNames={"HitMeButtonPrimary","HitMeButtonSecondary","HitMeButtonTertiary","HitMeIconButton","HitMeFeatureCard","HitMeCharacterCard","HitMeWeaponCard","HitMeMapCard"};
 public static readonly string[] PanelNames={"HitMeTopBar","HitMeBottomNavigation","HitMePopup","HitMePlayerHUD","HitMeChatPanel","HitMeCharacterSelection","HitMeWeaponSelection","HitMeMapSelection"};
 static UIThemeDefinition theme;
 [MenuItem("HIT ME/Configure UI Kit")]
 public static void Configure(){MainMenuAssetSetup.Configure();Directory.CreateDirectory(Root);theme=AssetDatabase.LoadAssetAtPath<UIThemeDefinition>("Assets/HitMe/Resources/UI/MainMenuTheme.asset");
  foreach(var name in WidgetNames){var go=Widget(name);Save(go,Root+name+".prefab");}
  foreach(var name in PanelNames){var go=Panel(name);Save(go,Root+name+".prefab");}
  Directory.CreateDirectory("Assets/HitMe/Prefabs/UI/Showcase");var showcase=Rect("UIShowcase",null,390,844);showcase.AddComponent<UIShowcaseController>();
  var scroll=new GameObject("Scroll",typeof(RectTransform),typeof(Image),typeof(ScrollRect));scroll.transform.SetParent(showcase.transform,false);Stretch(scroll.GetComponent<RectTransform>());scroll.GetComponent<Image>().color=new Color(.1f,.15f,.15f);var viewport=new GameObject("Viewport",typeof(RectTransform),typeof(RectMask2D));viewport.transform.SetParent(scroll.transform,false);Stretch(viewport.GetComponent<RectTransform>());
  var content=new GameObject("Content",typeof(RectTransform),typeof(VerticalLayoutGroup),typeof(ContentSizeFitter));content.transform.SetParent(viewport.transform,false);var cr=content.GetComponent<RectTransform>();cr.anchorMin=new Vector2(0,1);cr.anchorMax=Vector2.one;cr.pivot=new Vector2(.5f,1);cr.sizeDelta=Vector2.zero;var layout=content.GetComponent<VerticalLayoutGroup>();layout.padding=new RectOffset(20,20,20,20);layout.spacing=16;layout.childControlHeight=layout.childControlWidth=true;layout.childForceExpandHeight=false;content.GetComponent<ContentSizeFitter>().verticalFit=ContentSizeFitter.FitMode.PreferredSize;var sr=scroll.GetComponent<ScrollRect>();sr.viewport=viewport.GetComponent<RectTransform>();sr.content=cr;sr.horizontal=false;
  foreach(var name in WidgetNames){foreach(WidgetState state in System.Enum.GetValues(typeof(WidgetState))){var instance=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Root+name+".prefab"),content.transform);instance.name=name+"_"+state;var widget=instance.GetComponent<HitMeWidget>();widget.initialState=state;widget.SetState(state);widget.title.text=name+" · "+state;widget.titleKey="";}}
  foreach(var name in PanelNames)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Root+name+".prefab"),content.transform);
  Save(showcase,"Assets/HitMe/Prefabs/UI/Showcase/UIShowcase.prefab");AssetDatabase.SaveAssets();Debug.Log("HITME_UI_KIT: 16 independent prefabs + showcase generated with existing fallback sprites; no concept imports.");}
 static GameObject Rect(string name,Transform parent,float width,float height){var go=new GameObject(name,typeof(RectTransform),typeof(LayoutElement));go.transform.SetParent(parent,false);go.GetComponent<RectTransform>().sizeDelta=new Vector2(width,height);go.GetComponent<LayoutElement>().preferredHeight=height;return go;}
 static void Stretch(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
 static TMP_Text Text(Transform parent,string name,string key,float y,float height=30){var go=Rect(name,parent,290,height);go.GetComponent<RectTransform>().anchoredPosition=new Vector2(0,y);var t=go.AddComponent<TextMeshProUGUI>();t.font=Resources.Load<TMP_FontAsset>("Fonts/NunitoSDF");t.fontSize=16;t.enableAutoSizing=true;t.fontSizeMin=11;t.fontSizeMax=18;t.alignment=TextAlignmentOptions.Center;t.color=theme.cream;t.raycastTarget=false;t.text=string.IsNullOrEmpty(key)?"":Strings.Get(key);return t;}
 static GameObject Widget(string name){bool card=name.Contains("Card"),iconOnly=name.Contains("Icon");var go=Rect(name,null,iconOnly?48:326,card?116:48);var w=go.AddComponent<HitMeWidget>();w.theme=theme;w.background=go.AddComponent<Image>();w.background.sprite=name.Contains("Primary")?theme.paper:name.Contains("Secondary")?theme.brick:theme.card;w.background.type=Image.Type.Sliced;w.action=go.AddComponent<Button>();w.action.targetGraphic=w.background;var colors=w.action.colors;colors.pressedColor=new Color(.77f,.72f,.63f);colors.disabledColor=new Color(.46f,.46f,.46f,.8f);colors.fadeDuration=.16f;w.action.colors=colors;go.AddComponent<MenuInteraction>();
  w.titleKey="back";w.title=Text(go.transform,"Title","back",card?-24:0);w.title.rectTransform.sizeDelta=new Vector2(iconOnly?44:300,30);if(iconOnly)w.title.gameObject.SetActive(false);w.detail=Text(go.transform,"Detail","",card?-46:0,22);if(!card)w.detail.gameObject.SetActive(false);
  var icon=Rect("Icon",go.transform,36,36);icon.GetComponent<RectTransform>().anchoredPosition=new Vector2(0,card?25:0);w.icon=icon.AddComponent<Image>();w.icon.sprite=theme.Icon(iconOnly?"settings":"map");w.icon.preserveAspect=true;w.icon.raycastTarget=false;icon.SetActive(card||iconOnly);
  w.badge=Rect("Badge",go.transform,12,12);w.badge.GetComponent<RectTransform>().anchoredPosition=new Vector2(iconOnly?17:148,iconOnly?17:40);w.badge.AddComponent<Image>().color=Color.red;w.badge.SetActive(false);
  w.loading=Text(go.transform,"Loading","menuLoading",0).gameObject;if(name.Contains("Primary")){w.title.color=theme.dark;w.loading.GetComponent<TMP_Text>().color=theme.dark;}w.loading.SetActive(false);w.selection=Rect("Selected",go.transform,6,card?100:40);w.selection.GetComponent<RectTransform>().anchoredPosition=new Vector2(iconOnly?-20:-158,0);w.selection.AddComponent<Image>().color=theme.cream;w.selection.SetActive(false);return go;}
 static GameObject Panel(string name){bool nav=name.Contains("Navigation"),top=name.Contains("TopBar"),hud=name.Contains("HUD"),selection=name.Contains("Selection"),chat=name.Contains("Chat");float height=nav||top||hud?84:selection?440:chat?260:240;var go=Rect(name,null,350,height);var p=go.AddComponent<HitMePanel>();var im=go.AddComponent<Image>();im.sprite=theme.ink;im.type=Image.Type.Sliced;p.headingKey=chat?"chat":selection?"inventory":top?"profile":hud?"ready":nav?"":"back";p.heading=Text(go.transform,"Heading",p.headingKey,height/2-24);p.body=Text(go.transform,"Body","",height/2-56);p.value=Text(go.transform,"Value","",0);if(nav){p.heading.gameObject.SetActive(false);p.body.gameObject.SetActive(false);p.value.gameObject.SetActive(false);}if(selection){p.value.gameObject.SetActive(false);p.body.gameObject.SetActive(false);}if(!nav&&!top&&!hud&&!selection){p.value.gameObject.SetActive(false);p.body.rectTransform.anchoredPosition=new Vector2(0,chat?55:0);p.body.rectTransform.sizeDelta=new Vector2(290,chat?54:104);}if(top||hud){p.heading.rectTransform.anchoredPosition=new Vector2(-24,24);p.body.rectTransform.anchoredPosition=new Vector2(-24,0);p.value.rectTransform.anchoredPosition=new Vector2(-24,-24);p.heading.rectTransform.sizeDelta=new Vector2(240,24);}
  var items=new List<HitMeWidget>();if(nav||selection){string[] keys=nav?new[]{"menuHome","menuShop","inventory","menuTravel","menuCommunity"}:new[]{"menuCharacters","menuMaps","inventory"};for(int i=0;i<keys.Length;i++){var child=Widget(selection?(name.Contains("Character")?"HitMeCharacterCard":name.Contains("Weapon")?"HitMeWeaponCard":"HitMeMapCard"):"HitMeIconButton");child.transform.SetParent(go.transform,false);child.GetComponent<RectTransform>().anchoredPosition=nav?new Vector2(-136+i*68,-6):new Vector2(0,110-i*124);var w=child.GetComponent<HitMeWidget>();w.titleKey=keys[i];w.title.gameObject.SetActive(true);w.RefreshLocalization();if(nav){w.icon.gameObject.SetActive(false);w.title.fontSizeMax=12;w.title.fontSizeMin=9;}items.Add(w);}}
  else if(top||hud){var child=Widget("HitMeIconButton");child.transform.SetParent(go.transform,false);child.GetComponent<RectTransform>().anchoredPosition=new Vector2(145,0);items.Add(child.GetComponent<HitMeWidget>());p.body.rectTransform.sizeDelta=new Vector2(240,24);p.value.rectTransform.sizeDelta=new Vector2(240,24);}
  else{var confirm=Widget("HitMeButtonPrimary");confirm.transform.SetParent(go.transform,false);confirm.GetComponent<RectTransform>().sizeDelta=new Vector2(150,48);confirm.GetComponent<RectTransform>().anchoredPosition=new Vector2(-80,-height/2+34);var cw=confirm.GetComponent<HitMeWidget>();cw.title.rectTransform.sizeDelta=new Vector2(140,30);cw.titleKey=chat?"chat":"ready";cw.RefreshLocalization();p.confirm=cw.action;items.Add(cw);var cancel=Widget("HitMeButtonTertiary");cancel.transform.SetParent(go.transform,false);cancel.GetComponent<RectTransform>().sizeDelta=new Vector2(150,48);cancel.GetComponent<RectTransform>().anchoredPosition=new Vector2(80,-height/2+34);var xw=cancel.GetComponent<HitMeWidget>();xw.title.rectTransform.sizeDelta=new Vector2(140,30);p.cancel=xw.action;items.Add(xw);
   if(chat){var input=Rect("Input",go.transform,306,48);input.GetComponent<RectTransform>().anchoredPosition=new Vector2(0,-30);input.AddComponent<Image>().color=new Color(.25f,.3f,.27f);p.input=input.AddComponent<TMP_InputField>();var area=Rect("TextArea",input.transform,286,44);area.AddComponent<RectMask2D>();var t=Text(area.transform,"Text","",0,40);t.rectTransform.sizeDelta=new Vector2(276,40);p.input.textViewport=area.GetComponent<RectTransform>();p.input.textComponent=(TextMeshProUGUI)t;p.input.characterLimit=256;}}
  p.items=items.ToArray();p.selectOnClick=nav||selection;if(hud){p.heading.gameObject.SetActive(false);p.roundLabel=Text(go.transform,"Round","round",24,24);p.roundLabel.rectTransform.sizeDelta=new Vector2(120,24);p.roundLabel.rectTransform.anchoredPosition=new Vector2(-100,24);p.timerLabel=Text(go.transform,"Timer","",24,24);p.timerLabel.rectTransform.sizeDelta=new Vector2(70,24);p.timerLabel.rectTransform.anchoredPosition=new Vector2(20,24);}return go;}
 static void Save(GameObject go,string path){if(go.GetComponent<Canvas>()!=null){var r=go.GetComponent<RectTransform>();r.localScale=Vector3.one;r.anchorMin=r.anchorMax=r.pivot=new Vector2(.5f,.5f);r.sizeDelta=new Vector2(390,844);}PrefabUtility.SaveAsPrefabAsset(go,path);Object.DestroyImmediate(go);}
}
}




