using UnityEngine;
using UnityEngine.UI;
using HitMe.Visuals;
namespace HitMe.UI {
public sealed partial class MainMenuView {
 void InstallMapThumbnail(HitMeWidget card,ArenaArtDefinition map){if(card.selection!=null){var marker=card.selection.GetComponent<RectTransform>();marker.anchorMin=marker.anchorMax=new Vector2(0,.5f);marker.pivot=new Vector2(0,.5f);marker.anchoredPosition=new Vector2(3,0);marker.sizeDelta=new Vector2(3,92);}card.icon.gameObject.SetActive(false);if(map?.previewSprite==null)return;var slot=R(card.transform,"ThumbnailViewport",0,8,128,42);slot.gameObject.AddComponent<RectMask2D>();var image=R(slot,"Artwork",0,0,128,42).gameObject.AddComponent<Image>();image.sprite=map.previewSprite;image.raycastTarget=false;image.gameObject.AddComponent<ImageCover>();}
 public void Maps(){var panel=Modal("menuMaps",600,MenuPanel.Maps);int[] order={0,6,2,1,3,4,5};for(int n=0;n<order.Length;n++){int index=order[n];var map=ArenaMaps.Load(index);var card=HitMeWidgetFactory.Create("HitMeMapCard",panel);card.name="Map"+index;var r=card.GetComponent<RectTransform>();r.anchorMin=r.anchorMax=new Vector2(.5f,1);r.pivot=new Vector2(.5f,1);r.anchoredPosition=new Vector2(n%2==0?-83:83,-72-n/2*108);r.sizeDelta=new Vector2(158,100);card.Bind(map!=null?map.DisplayName:L("map"+ArenaMaps.Ids[index]),L(map!=null&&map.ArtworkReady?"mapArtPartial":"missingArenaArt"),map?.previewSprite);InstallMapThumbnail(card,map);card.icon.rectTransform.anchoredPosition=new Vector2(0,23);card.title.rectTransform.anchoredPosition=new Vector2(0,-12);card.title.rectTransform.sizeDelta=new Vector2(146,27);card.title.fontSizeMax=12;card.title.fontSizeMin=10;card.detail.rectTransform.anchoredPosition=new Vector2(0,-38);card.detail.rectTransform.sizeDelta=new Vector2(146,18);card.detail.fontSizeMax=10;card.SetState(ArenaMaps.Selected==index?WidgetState.Selected:WidgetState.Normal);card.activated.AddListener(()=>MapPreview(index));}T(panel,"MapPolicy",L("mapOfflinePolicy"),0,522,310,62,11,theme.muted);}
 public void MapPreview(int index){var map=ArenaMaps.Load(index);var panel=Modal("menuMaps",570,MenuPanel.Maps);T(panel,"MapName",map!=null?map.DisplayName:L("map"+ArenaMaps.Ids[index]),0,66,306,28,18,theme.cream);var preview=R(panel,"MapAnimatedPreview",0,100,300,284);preview.gameObject.AddComponent<RectMask2D>();var bg=R(preview,"MapPreviewBackground",0,0,300,284).gameObject.AddComponent<Image>();bg.sprite=map?.backdrop;bg.color=map?.backdrop!=null?Color.white:new Color(.13f,.17f,.19f);bg.raycastTarget=false;if(bg.sprite!=null)bg.gameObject.AddComponent<ImageCover>();var floor=R(preview,"MapPreviewFloor",0,32,126,220).gameObject.AddComponent<Image>();floor.sprite=map?.floorSprite;floor.type=Image.Type.Tiled;floor.pixelsPerUnitMultiplier=2;floor.raycastTarget=false;floor.enabled=floor.sprite!=null;var motion=preview.gameObject.AddComponent<MapMotionController>();motion.Initialize(map);T(panel,"MapArtworkStatus",L(map!=null&&map.ArtworkReady?"mapArtPartial":"mapFallbackPreview"),0,399,306,40,12,theme.cream);T(panel,"MapOnlineStatus",L("mapOfflinePolicy"),0,438,306,35,11,theme.muted);var confirm=Row(panel,"ConfirmMap",L(map!=null&&map.ArtworkReady?"mapConfirm":"mapConfirmFallback"),492,()=>{ArenaMaps.Selected=index;Maps();});confirm.interactable=map!=null&&map.CanUseOffline;}
}
}
