using System.Collections;
using System.IO;
using NUnit.Framework;
using HitMe.UI;
using HitMe.Visuals;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
namespace HitMe.Tests {
public sealed class MapKitFlowTests {
 [UnityTest] public IEnumerator MapMotionHonorsFocusQualityReducedMotionAndTouch(){var quality=MotionSettings.Quality;bool reduced=MotionSettings.Reduced;MotionSettings.Quality=MotionQuality.High;MotionSettings.Reduced=false;var root=new GameObject("MotionPolicyTest",typeof(RectTransform),typeof(MapMotionController));var motion=root.GetComponent<MapMotionController>();motion.Initialize(ArenaMaps.Load(0));yield return null;Assert.AreEqual(4,motion.LayerCount);var layers=root.GetComponentsInChildren<EnvironmentLayerView>(true);foreach(var layer in layers)Assert.IsFalse(layer.GetComponent<Image>().raycastTarget);motion.SetFocused(true);yield return null;foreach(var layer in layers)Assert.IsFalse(layer.enabled);motion.SetFocused(false);yield return null;foreach(var layer in layers)Assert.IsTrue(layer.enabled);MotionSettings.Reduced=true;yield return null;foreach(var layer in layers)Assert.IsFalse(layer.enabled);MotionSettings.Reduced=false;MotionSettings.Quality=MotionQuality.Low;yield return null;int visible=0;foreach(var layer in layers)if(layer.gameObject.activeSelf)visible++;Assert.AreEqual(1,visible);Object.Destroy(root);MotionSettings.Quality=quality;MotionSettings.Reduced=reduced;yield return null;LogAssert.NoUnexpectedReceived();}
 static void Capture(string name){var image=ScreenCapture.CaptureScreenshotAsTexture();File.WriteAllBytes(Path.GetFullPath(Path.Combine(Application.dataPath,"../../docs/screenshots/"+name+".png")),image.EncodeToPNG());Object.Destroy(image);}
 [UnityTest] public IEnumerator PreviewRequiresConfirmationAndMissingLocationsAreLabeled(){int saved=ArenaMaps.Selected;ArenaMaps.Selected=0;Strings.Load("vi");SceneManager.LoadScene("MainMenu");yield return null;yield return null;yield return null;var view=Object.FindAnyObjectByType<MainMenuView>();view.Maps();yield return null;Capture("Map-Selection");view.MapPreview(6);yield return null;Assert.AreEqual(0,ArenaMaps.Selected);Assert.IsNotNull(view.Content.Find("MenuModal/Panel/MapArtworkStatus"));Capture("Map-HoiAn-Fallback-Preview");view.Content.Find("MenuModal/Panel/ConfirmMap").GetComponent<Button>().onClick.Invoke();yield return null;Assert.AreEqual(6,ArenaMaps.Selected);var selected=view.Content.Find("MenuModal/Panel/Map6").GetComponent<HitMeWidget>();Assert.AreEqual(WidgetState.Selected,selected.State);var bounds=RectTransformUtility.CalculateRelativeRectTransformBounds(selected.transform,selected.selection.transform);var rect=((RectTransform)selected.transform).rect;Assert.GreaterOrEqual(bounds.min.x,rect.xMin);Assert.LessOrEqual(bounds.max.x,rect.xMax);Capture("Map-Selection-Confirmed");view.CloseModal();foreach(int index in new[]{0,6,2}){ArenaMaps.Selected=index;OfflineRunContext.Requested=false;SceneManager.LoadScene("Battle");yield return null;yield return null;yield return null;Assert.IsNotNull(GameObject.Find("ArenaSandSprite").GetComponent<Image>().sprite);Assert.IsNotNull(Object.FindAnyObjectByType<MapMotionController>());if(index!=0)Assert.That(GameObject.Find("ArenaLabel").GetComponent<Text>().text,Does.Contain(Strings.Get("missingArenaArt")));Capture(index==0?"Map-BacBo-Actual":"Map-"+(index==6?"HoiAn":"HaLong")+"-Fallback");}ArenaMaps.Selected=saved;SceneManager.LoadScene("MainMenu");yield return null;LogAssert.NoUnexpectedReceived();}
}
}
