using System.Collections;
using HitMe.UI;
using HitMe.Visuals;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
namespace HitMe.Tests {
public sealed class Phase2APolishTests {
 string savedEndpoint;
 [UnitySetUp]public IEnumerator IsolateConnection(){savedEndpoint=PlayerPrefs.GetString("NetworkEndpoint","");PlayerPrefs.SetString("NetworkEndpoint","ws://127.0.0.1:1/play");if(NetworkSession.Instance!=null)Object.Destroy(NetworkSession.Instance.gameObject);yield return null;}
 [UnityTearDown]public IEnumerator RestoreConnection(){PlayerPrefs.SetString("NetworkEndpoint",savedEndpoint);if(NetworkSession.Instance!=null)Object.Destroy(NetworkSession.Instance.gameObject);yield return null;}
 [UnityTest]public IEnumerator PointerDebounceAndReducedMotion(){var go=Object.Instantiate(Resources.Load<GameObject>("UI/Kit/HitMeButtonPrimary"));var b=go.GetComponent<DebouncedButton>();int clicks=0;b.onClick.AddListener(()=>clicks++);var evt=new PointerEventData(EventSystem.current){button=PointerEventData.InputButton.Left};b.OnPointerClick(evt);b.OnPointerClick(evt);Assert.AreEqual(1,clicks);yield return new WaitForSecondsRealtime(.2f);b.OnPointerClick(evt);Assert.AreEqual(2,clicks);Object.Destroy(go);bool reduced=MotionSettings.Reduced;MotionSettings.Reduced=true;var popup=Object.Instantiate(Resources.Load<GameObject>("UI/Kit/HitMePopup"));Assert.IsFalse(popup.GetComponent<UIMotionController>().Transitioning);Assert.IsTrue(popup.GetComponent<CanvasGroup>().interactable);Object.Destroy(popup);MotionSettings.Reduced=reduced;}
 [UnityTest]public IEnumerator SelectionThenBattleHudAndUnavailableChat(){int character=CosmeticPreview.Character,weapon=CosmeticPreview.Weapon;
  try{SceneManager.LoadScene("MainMenu");yield return null;yield return null;var v=Object.FindAnyObjectByType<MainMenuView>();v.Characters();yield return new WaitForSecondsRealtime(.2f);var cards=v.Content.Find("MenuModal/Panel").GetComponentInChildren<HitMePanel>();cards.items[1].action.onClick.Invoke();Assert.AreEqual(character,CosmeticPreview.Character);v.Content.Find("MenuModal/Panel/ConfirmCharacter").GetComponent<UnityEngine.UI.Button>().onClick.Invoke();Assert.AreEqual(1,CosmeticPreview.Character);Assert.AreEqual(WidgetState.Selected,cards.items[1].State);v.CloseModal();v.Weapons();yield return new WaitForSecondsRealtime(.2f);var weapons=v.Content.Find("MenuModal/Panel").GetComponentInChildren<HitMePanel>();weapons.items[2].action.onClick.Invoke();Assert.AreEqual(2,CosmeticPreview.Weapon);v.CloseModal();
   OfflineRunContext.Requested=false;SceneManager.LoadScene("Battle");yield return null;yield return null;yield return null;var view=Object.FindAnyObjectByType<BattleView>();var visual=GameObject.Find("ActorFeet0").GetComponentInChildren<HitMe.Characters.CharacterVisual>();Assert.AreSame(CosmeticPreview.Definition,visual.Definition);Assert.AreSame(CosmeticPreview.WeaponDefinition,visual.Weapon);var portrait=GameObject.Find("PortraitPlaceholder0").transform.Find("PortraitSprite").GetComponent<UnityEngine.UI.Image>();Assert.AreSame(CosmeticPreview.Definition.portrait!=null?CosmeticPreview.Definition.portrait:CosmeticPreview.Definition.Frame(HitMe.Characters.VisualState.Idle,0),portrait.sprite);var hud=GameObject.Find("BattleHUDKit").GetComponent<HitMePanel>();Assert.IsNotNull(hud.roundLabel);Assert.IsFalse(hud.roundLabel.text.Contains("[round]"));GameObject.Find("Chat").GetComponent<UnityEngine.UI.Button>().onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);var chat=GameObject.Find("ChatUI").GetComponent<HitMePanel>();Assert.IsFalse(chat.input.interactable);Assert.IsFalse(chat.confirm.gameObject.activeSelf);chat.cancel.onClick.Invoke();yield return new WaitForSecondsRealtime(.24f);Assert.IsNull(GameObject.Find("ChatUI"));Assert.AreEqual(HitMe.Core.BattlePhase.LayoutPreview,view.Session.Phase);
   SceneManager.LoadScene("CharacterSelect");yield return null;yield return null;Assert.IsNotNull(Object.FindAnyObjectByType<CharacterSelectionView>());Assert.IsNotNull(Object.FindAnyObjectByType<HitMePanel>());
  }finally{CosmeticPreview.Character=character;CosmeticPreview.Weapon=weapon;}SceneManager.LoadScene("MainMenu");yield return null;LogAssert.NoUnexpectedReceived();}
}
}
