using System;
using System.Linq;
using HitMe.Core;
using NUnit.Framework;
namespace HitMe.Tests {
public class RoundedArenaTests {
 static FoundationConfig Config()=>new FoundationConfig{arenaShape="roundedRectangle",arenaWidth=2000,arenaHeight=3500,cornerRadius=300};
 [TestCase(0,0,true)][TestCase(1000,0,true)][TestCase(0,1750,true)][TestCase(1000,1750,false)][TestCase(910,1660,true)][TestCase(1001,0,false)][TestCase(-950,-1700,false)]
 public void PointInside(double x,double y,bool expected){Assert.AreEqual(expected,Config().ArenaGeometry.PointInside(new Point(x,y)));}
 [Test]public void ClampedPlayersKeepEntireCircularHitboxInside(){var g=Config().ArenaGeometry;for(int x=-1400;x<=1400;x+=100)for(int y=-2100;y<=2100;y+=100){var p=g.ClampPosition(new Point(x,y),90);Assert.IsTrue(g.PlayerPlacementValidation(p,90));for(int angle=0;angle<360;angle+=10){double a=angle*Math.PI/180;Assert.IsTrue(g.PointInside(new Point(p.X+90*Math.Cos(a),p.Y+90*Math.Sin(a))));}}}
 [Test]public void RaysExitStraightWallsAndRoundedCorners(){var g=Config().ArenaGeometry;foreach(var origin in new[]{new Point(),new Point(700,1450),new Point(-900,0)})for(int angle=0;angle<360;angle+=5){double a=angle*Math.PI/180;var d=new Point(Math.Cos(a),Math.Sin(a));var p=g.RayBoundaryIntersection(origin,d);Assert.IsTrue(g.PointInside(p));Assert.IsFalse(g.PointInside(new Point(p.X+d.X*.01,p.Y+d.Y*.01)));}}
 [Test]public void ProjectileRadiusStopsBeforeWall(){var g=Config().ArenaGeometry;for(int angle=0;angle<360;angle+=5){double a=angle*Math.PI/180;var d=new Point(Math.Cos(a),Math.Sin(a));var p=g.ProjectileCollision(new Point(),d,30);Assert.IsTrue(g.PlayerPlacementValidation(p,30));Assert.IsFalse(g.PlayerPlacementValidation(new Point(p.X+d.X*.01,p.Y+d.Y*.01),30));}}
 [Test]public void BoundaryOriginRayCanTravelInward(){var g=Config().ArenaGeometry;Assert.AreEqual(-1000,g.RayBoundaryIntersection(new Point(1000,0),new Point(-1,0)).X);Assert.AreEqual(1000,g.RayBoundaryIntersection(new Point(1000,0),new Point(1,0)).X);}
 [Test]public void InvalidGeometryAndDirectionsRejected(){Assert.Throws<ArgumentException>(()=>new RoundedRectangleArenaGeometry(2000,3500,1001));Assert.Throws<ArgumentException>(()=>Config().ArenaGeometry.RayBoundaryIntersection(new Point(),new Point()));Assert.IsFalse(Config().ArenaGeometry.PointInside(new Point(double.NaN,0)));}
 [Test]public void FirstTargetAndOneDamageArePreserved(){var c=Config();var r=CombatRules.Resolve(new[]{new FighterSnapshot("a",3),new FighterSnapshot("b",3),new FighterSnapshot("c",3)},new[]{new LockedAction("a",new Point(-500,1500),new Point(1,0)),new LockedAction("b",new Point(0,1500),new Point(),false),new LockedAction("c",new Point(500,1500),new Point(),false)},c);Assert.AreEqual("b",r.Throws[0].Target);Assert.AreEqual(2,r.Health.Single(x=>x.Id=="b").HPAfter);Assert.AreEqual(3,r.Health.Single(x=>x.Id=="c").HPAfter);}
 [Test]public void SimultaneousLastHitsStillDraw(){var r=CombatRules.Resolve(new[]{new FighterSnapshot("a",1),new FighterSnapshot("b",1)},new[]{new LockedAction("a",new Point(-200,0),new Point(1,0)),new LockedAction("b",new Point(200,0),new Point(-1,0))},Config());Assert.AreEqual(MatchOutcome.Draw,r.Outcome);Assert.IsNull(r.Winner);}
 [Test]public void TimeoutAutoLocksCompleteInputAndReveals(){var m=new OfflineMatch(Config(),new MatchSettings{BotCount=1,Timeout=TimeoutPolicy.ProposedStayAndSkip},0);m.Place("player",new Point(),.1);m.Aim("player",new Point(1,0),.1);Assert.IsNull(m.ViewFor("player")[1].Action);m.Tick(5);Assert.AreEqual(MatchPhase.Reveal,m.Phase);Assert.AreEqual(InputStage.Locked,m.ViewFor("player")[0].Stage);Assert.IsNotNull(m.ViewFor("player")[1].Action);}
 [Test]public void RevealWaitsForEveryLivingLock(){var m=new OfflineMatch(Config(),new MatchSettings{BotCount=1},0);foreach(var id in m.Ids){m.Place(id,new Point(),.1);m.Aim(id,new Point(1,0),.1);}m.Lock("player",.1);Assert.AreEqual(MatchPhase.Placement,m.Phase);m.Lock("bot-1",.2);Assert.AreEqual(MatchPhase.Reveal,m.Phase);}
 [Test]public void SeededBotPlacementRemainsValid(){var rng=new SeededRandom(42);var c=Config();for(int i=0;i<1000;i++)Assert.IsTrue(c.ArenaGeometry.PlayerPlacementValidation(BotController.RandomPosition(rng,c),90));}
 [Test]public void EllipseRollbackRetainsOriginalBoundary(){var c=Config();c.arenaShape="ellipse";Assert.IsInstanceOf<EllipseArenaGeometry>(c.ArenaGeometry);Assert.That(c.ArenaGeometry.RayBoundaryIntersection(new Point(),new Point(1,0)).X,Is.EqualTo(1000).Within(1e-8));}
 [Test]public void PublicSnapshotsStayImmutableAndPrivateAfterCacheInvalidation(){var m=new OfflineMatch(Config(),new MatchSettings{BotCount=1},0);var before=m.ViewFor("player");Assert.AreSame(before,m.ViewFor("player"));m.Place("bot-1",new Point(400,500),.1);m.Aim("bot-1",new Point(1,0),.1);Assert.IsNull(m.ViewFor("player")[1].Action);Assert.IsNotNull(m.ViewFor("bot-1")[1].Action);m.Place("player",new Point(-300,0),.2);Assert.IsNull(before[0].Action);Assert.AreEqual(-300,m.ViewFor("player")[0].Action.Position.X);m.Aim("player",new Point(1,0),.2);m.Lock("player",.2);m.Lock("bot-1",.2);Assert.IsNotNull(m.ViewFor("player")[1].Action);Assert.IsNull(before[1].Action);}

}}
